# Generated by Django 4.2.1 on 2023-05-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='more_service_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='services',
            name='more_service_question',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='services',
            name='more_service_text',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='What_i_provide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=100)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.services')),
            ],
        ),
    ]
