# Generated by Django 4.2.1 on 2023-06-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_alter_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(default='', max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('portfolio_text', models.TextField()),
            ],
        ),
    ]
